version: 0.2

phases:
  pre_build:
    commands:
      - |
        # Check for changes in the html/ directory
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
        if echo "$CHANGED_FILES" | grep -qvE 'html/'; then
          echo "No changes in html/ directory. Skipping build."
          exit 1
        else
          echo "Changes detected in html/ directory. Continuing build."
        fi
  build:
    commands:
      - echo "Uploading file to S3..."
      #- env
      - aws s3 cp html/sample.html s3://$S3_BUCKET/sample-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8).html
      - echo "Updating SSM Parameter..."
      - aws ssm put-parameter --name $SSM_PATH --value "sample-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8).html" --type String --overwrite
      - aws s3 cp s3://$S3_BUCKET/codedeploy/test.json task.json
      - sed -i -e "s/sample-.*/sample-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8).html\"/g" task.json
      - cat task.json
      - aws ecs register-task-definition --cli-input-json file://task.json > result.json
      - cat result.json
      - /bin/sh update-appspec.sh

artifacts:
  files:
    - html/sample.html
    - appspec.yaml  
